CREATE DATABASE BookingDB;
USE BookingDB;

CREATE TABLE Seats (
    SeatID INT PRIMARY KEY,
    IsBooked BIT
);

INSERT INTO Seats VALUES (101, 0);

-- T1
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION;

IF (SELECT IsBooked FROM Seats WHERE SeatID = 101) = 0
BEGIN
    UPDATE Seats SET IsBooked = 1 WHERE SeatID = 101;
    COMMIT;
END
ELSE
    ROLLBACK;

-- T2
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION;

IF (SELECT IsBooked FROM Seats WHERE SeatID = 101) = 0
BEGIN
    UPDATE Seats SET IsBooked = 1 WHERE SeatID = 101;
    COMMIT;
END
ELSE
    ROLLBACK;